### ISSUE TITLE
Pobieranie z NBP informacji z okresu dłuższego niż 367 dni kończy się błędem

### ISSUE THREAD

**Issue by klima7** [IIS-ZPI/ZPI2020_IO1_Codesalmon#51]
Gdy do funkcji pobierającej dane z NBP podaj się okres dłuższy niż 367 dni to z niejasnych powodów pojawia się następujący błąd

> Traceback (most recent call last):
  File "C:\Users\ukasz\PycharmProjects\ZPI2020_IO1_Codesalmon3\src\__init__.py", line 10, in <module>
    main()
  File "C:\Users\ukasz\PycharmProjects\ZPI2020_IO1_Codesalmon3\src\__init__.py", line 6, in main
    print(stats.get_data_in_time("USD", 500))
  File "C:\Users\ukasz\PycharmProjects\ZPI2020_IO1_Codesalmon3\src\nbp_stats.py", line 24, in get_data_in_time
    data = requests.get(request_string).json()
  File "C:\Users\ukasz\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\ukasz\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\ukasz\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

**Comment by klima7** [comment]
Okazuje się, że API NBP nie akceptuje większej liczby dni niż 367. Należy jednak w przypadku wywołania funkcji z niepoprawną liczbą dni zwrócić jasny komunikat o błędzie.

**Comment by klima7** [comment]
Błąd został naprawiony. W przypadku zbyt dużej liczby dni wyrzucany jest błąd `InvalidDaysCountException`
