### ISSUE TITLE
Pobieranie danych z NPM z ujemną liczbą dni kończy się niejasnym błędem

### ISSUE THREAD

**Issue by klima7** [IIS-ZPI/ZPI2020_IO1_Codesalmon#52]
Gdy funkcji pobierająca dane z interfejsu NBP jest wywoływana z ujemnym okresem to zwracany jest bardzo niejasny komunikat o błędzie. Funkcja ta oczywiście nie powinna być wywoływana z ujemnymi wartościami, lecz jeśli tak się stanie to dobrze jest zwrócić jasną informację o przyczynie błędu.

Kroki odtworzenia:
- Wywołanie funkcji get_data_in_time z przykładową walutą 'USD' oraz przykładowym okresem -4.
- Aplikacji wyświetla informacje o błędzie.

Zwracany błąd:
> Traceback (most recent call last):
  File "C:\Users\ukasz\PycharmProjects\ZPI2020_IO1_Codesalmon3\src\__init__.py", line 10, in <module>
    main()
  File "C:\Users\ukasz\PycharmProjects\ZPI2020_IO1_Codesalmon3\src\__init__.py", line 6, in main
    print(stats.get_data_in_time('USD', -1))
  File "C:\Users\ukasz\PycharmProjects\ZPI2020_IO1_Codesalmon3\src\nbp_stats.py", line 24, in get_data_in_time
    data = requests.get(request_string).json()
  File "C:\Users\ukasz\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\ukasz\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\ukasz\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

Odpowiedni test został dodany do zestawu, aplikacja powinna rzucać w tym przypadku wyjątek `InvalidDaysCount`

**Comment by klima7** [comment]
Błąd został naprawiony, w omówionej sytuacji rzucany jest wyjątek `InvalidDaysCount`
